### ISSUE TITLE
Can't build on Visual Studio 2015

### ISSUE THREAD

**Issue by euglv** [ivere27/toby#1]
I followed build instructions, but got error:
```
toby.cpp(344): error C2131: expression did not evaluate to a constant
toby.cpp(344): note: failure was caused by non-constant arguments or reference to a non-constant symbol
toby.cpp(344): note: see usage of 'args'
```
Using Visual Studio 2015 and Windows 10

**Comment by ivere27** [comment]
sorry for the bug in MSVC
I uploaded a patch. please try it again

https://github.com/ivere27/toby/commit/1dfd9fbb2ad1718071df8a554669bd5c268485e0
