### ISSUE TITLE
License

### ISSUE THREAD

**Issue by czhower** [ivere27/toby#2]
Sorry to post here, but GitHub removed private messaging in 2012 and few GH user publish their emails (for good reasons).

Would you consider re-licensing this under a more permissive license? AGPL basically makes it useless except in an infectious manner. Users cannot even use your DLL without themselves also being AGPL (or compatible). If it were at least LGPL then it would be far more usable.

**Comment by ivere27** [comment]
That's right. I'll change it.

**Comment by ivere27** [comment]
https://github.com/ivere27/toby/commit/b21e9446d85ff4091c9baedfecfeda1bdb1a0d0a

now MIT license. hope you use the toby project well. :)

**Comment by czhower** [comment]
Thank you very very much! Would you be so kind as to alter the node-Delphi repo as well?

**Comment by ivere27** [comment]
done it

**Comment by czhower** [comment]
Thank you very much!!!!
